accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path("register/", views.signup, name="register"),
    path('logout/', views.user_logout, name='logout'),
]

ticket_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('ticketapp.urls')),
]

ticketapp/urls.py
from django.urls import path
from . import views

app_name = 'ticketapp'

urlpatterns = [
    path('', views.TicketListView.as_view(), name='ticket-list'),
    path('ticket-detail/<int:pk>/',
         views.TicketDetailView.as_view(), name='ticket-detail'),
    path('create-ticket/', views.TicketCreateView.as_view(), name='create-ticket'),
    path('update-ticket/<int:pk>/',
         views.TicketUpdateView.as_view(), name='update-ticket'),
    path('delete-ticket/<int:pk>/',
         views.TicketDeleteView.as_view(), name='delete-ticket'),
    path('all-tickets/', views.ticket_list, name='all-tickets'),
    path('resolved-tickets/', views.resolved_tickets, name='resolved-tickets'),
    path('unresolved-tickets/', views.unresolved_tickets,
         name='unresolved-tickets'),
    path('urgent-tickets/', views.urgent_ticket_list, name='urgent-tickets'),
    path('mark-resolved/<int:id>',
         views.mark_ticket_as_resolved, name='mark-resolved'),
    path('mark-unresolved/<int:id>',
         views.mark_ticket_as_unresolved, name='mark-unresolved'),
    path('add-comment/<int:ticket_id>/', views.add_comment, name='add-comment'),
    path('search/', views.SearchResultView.as_view(), name='search'),
    path('search-results/', views.StaffSearchResultView.as_view(),
         name='search-results'),
    path('search-all/', views.AllSearchResultView.as_view(), name='search-all'),

    # user statistics page
    path('user-statistics/', views.UserPerformanceListView.as_view(),
         name='user-performance-list'),
    path('user-statistics/user-detail/<str:username>/',
         views.user_performance_details, name='user-performance-detail'),

    path("get-emails/", views.get_emails, name="get-emails"),
]

ticketapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import PasswordInput
from django.urls import reverse
from django.utils.crypto import get_random_string

# Create your models here.


class Ticket(models.Model):

    TICKET_SECTIONS = (
        ('Software', 'Software'),
        ('Hardware', 'Hardware'),
        ('Applications', 'Applications'),
        ('Infrastructure and Networking', 'Infrastructure and Networking'),
        ('Database Administrator', 'Database Administrator')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ticket_id = models.CharField(max_length=8, unique=True, blank=True)
    title = models.CharField(max_length=50)
    customer_full_name = models.CharField(max_length=200)
    customer_phone_number = models.CharField(max_length=20)
    customer_email = models.EmailField(max_length=40)
    issue_description = models.TextField(max_length=1000)
    ticket_section = models.CharField(
        max_length=30, choices=TICKET_SECTIONS, null=True, blank=True)
    urgent_status = models.BooleanField(default=False)
    completed_status = models.BooleanField(default=False)
    assigned_to = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='assigned_to', null=True, blank=True)
    resolved_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='resolved_by', null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    resolved_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.title

    def generate_client_id(self):
        return get_random_string(8, allowed_chars='0123456789abcdefzxyv')

    def get_absolute_url(self):
        return reverse("ticketapp:ticket-detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        self.ticket_id = self.generate_client_id()
        super(Ticket, self).save(*args, **kwargs)


class Comment(models.Model):
    ticket = models.OneToOneField(Ticket, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    created_date = models.DateTimeField(null=True, auto_now_add=True)


class EmailDetails(models.Model):
    email = models.EmailField(max_length=254)
    password = models.CharField(max_length=254)

    def __str__(self):
        return self.email

ticketapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Ticket


class TicketForm(forms.ModelForm):
    title = forms.CharField(max_length=50, widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    customer_full_name = forms.CharField(
        max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    customer_phone_number = forms.CharField(
        max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
    customer_email = forms.CharField(
        max_length=40, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    issue_description = forms.CharField(
        max_length=100, widget=forms.Textarea(attrs={'class': 'form-control'}))
    assigned_to = forms.ModelChoiceField(
        queryset=User.objects.all(), empty_label='Select User', widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Ticket
        exclude = ('user', 'ticket_id', 'created_date',
                   'completed_status', 'resolved_by', 'resolved_date')


class TicketUpdateForm(forms.ModelForm):

    TICKET_SECTIONS = (
        ('Software', 'Software'),
        ('Hardware', 'Hardware'),
        ('Applications', 'Applications'),
        ('Infrastructure and Networking', 'Infrastructure and Networking'),
        ('Database Administrator', 'Database Administrator')
    )

    title = forms.CharField(max_length=50, widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    customer_full_name = forms.CharField(
        max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    customer_phone_number = forms.CharField(
        max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
    customer_email = forms.CharField(
        max_length=40, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    issue_description = forms.CharField(
        max_length=100, widget=forms.Textarea(attrs={'class': 'form-control'}))
    ticket_section = forms.ChoiceField(
        choices=TICKET_SECTIONS, widget=forms.Select(attrs={'class': 'form-control'}))
    assigned_to = forms.ModelChoiceField(
        queryset=User.objects.all(), empty_label='Select User', widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Ticket
        exclude = ('user', 'ticket_id', 'created_date',
                   'resolved_by', 'resolved_date')

ticketapp/views.py
import datetime
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Count
from django.core.mail import send_mail
from django.conf import settings
from .models import Ticket, Comment, EmailDetails
from .forms import TicketForm, TicketUpdateForm

from .get_email import EmailDownload

# Create your views here.


class TicketListView(LoginRequiredMixin, generic.ListView):
    model = Ticket
    template_name = "ticketapp/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_superuser:
            context["all_issues"] = Ticket.objects.all().count()
            context["urgent_count"] = Ticket.objects.filter(urgent_status=True).count()
            context["resolved_count"] = Ticket.objects.filter(
                completed_status=True
            ).count()
            context["unresolved_count"] = Ticket.objects.filter(
                completed_status=False
            ).count()
            context["normal_user_list"] = Ticket.objects.filter(user=self.request.user)
            context["staff_user_list"] = Ticket.objects.filter(
                assigned_to=self.request.user
            )
            context["software_tickets"] = Ticket.objects.filter(
                ticket_section="Software"
            ).count()
            context["hardware_tickets"] = Ticket.objects.filter(
                ticket_section="Hardware"
            ).count()
            context["applications_tickets"] = Ticket.objects.filter(
                ticket_section="Applications"
            ).count()
            context["infracture_tickets"] = Ticket.objects.filter(
                ticket_section="Infrastructure and Networking"
            ).count()
            context["dbadmin_tickets"] = Ticket.objects.filter(
                ticket_section="Database Administrator"
            ).count()

        elif self.request.user.is_staff:
            context["all_issues"] = Ticket.objects.filter(
                assigned_to=self.request.user
            ).count()
            context["urgent_count"] = Ticket.objects.filter(
                assigned_to=self.request.user, urgent_status=True
            ).count()
            context["resolved_count"] = Ticket.objects.filter(
                assigned_to=self.request.user, completed_status=True
            ).count()
            context["unresolved_count"] = Ticket.objects.filter(
                assigned_to=self.request.user, completed_status=False
            ).count()
            context["normal_user_list"] = Ticket.objects.filter(user=self.request.user)
            context["staff_user_list"] = Ticket.objects.filter(
                assigned_to=self.request.user
            )

            context["software_tickets"] = Ticket.objects.filter(
                ticket_section="Software", assigned_to=self.request.user
            ).count()
            context["hardware_tickets"] = Ticket.objects.filter(
                ticket_section="Hardware", assigned_to=self.request.user
            ).count()
            context["applications_tickets"] = Ticket.objects.filter(
                ticket_section="Applications", assigned_to=self.request.user
            ).count()
            context["infracture_tickets"] = Ticket.objects.filter(
                ticket_section="Infrastructure and Networking",
                assigned_to=self.request.user,
            ).count()
            context["dbadmin_tickets"] = Ticket.objects.filter(
                ticket_section="Database Administrator", assigned_to=self.request.user
            ).count()

        return context


class TicketDetailView(LoginRequiredMixin, generic.DetailView):
    model = Ticket

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comments"] = Comment.objects.filter(ticket=self.get_object()).order_by(
            "-created_date"
        )
        return context


class TicketCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ticket
    form_class = TicketForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TicketUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ticket
    form_class = TicketUpdateForm
    template_name = "ticketapp/ticket_update.html"


class TicketDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ticket
    success_url = reverse_lazy("ticketapp:ticket-list")


@login_required
def ticket_list(request):
    tickets = Ticket.objects.all()
    return render(request, "ticketapp/allissues.html", {"tickets": tickets})


@login_required
def urgent_ticket_list(request):
    if request.user.is_superuser:
        tickets = Ticket.objects.filter(urgent_status=True)
    else:
        tickets = Ticket.objects.filter(assigned_to=request.user, urgent_status=True)
    return render(request, "ticketapp/urgent.html", {"tickets": tickets})


@login_required
def resolved_tickets(request):
    if request.user.is_superuser:
        tickets = Ticket.objects.filter(completed_status=True)
    else:
        tickets = Ticket.objects.filter(assigned_to=request.user, completed_status=True)
    return render(request, "ticketapp/closed.html", {"tickets": tickets})


@login_required
def unresolved_tickets(request):
    if request.user.is_superuser:
        tickets = Ticket.objects.filter(completed_status=False)
    else:
        tickets = Ticket.objects.filter(
            assigned_to=request.user, completed_status=False
        )
    return render(request, "ticketapp/open.html", {"tickets": tickets})


@login_required
def mark_ticket_as_resolved(request, id):
    if request.method == "POST":
        comment = request.POST["comment"]
        ticket = Ticket.objects.get(id=id)
        user = request.user
        date_time = datetime.datetime.now()
        ticket.resolved_by = user
        ticket.resolved_date = date_time
        ticket.completed_status
        Comment.objects.create(ticket=ticket, user=user, text=comment)
        Ticket.objects.filter(id=id).update(
            completed_status=True, resolved_by=user, resolved_date=date_time
        )

        subject = "Issue resolved"
        message = f"Good day.\n Please note your issue: \n{ticket.issue_description}\n has been resolved successfully\nRegards,\n ICT Helpdesk"
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [
            ticket.customer_email,
        ]
        send_mail(subject, message, email_from, recipient_list)

    return HttpResponseRedirect(reverse("ticketapp:ticket-detail", kwargs={"pk": id}))


@login_required
def mark_ticket_as_unresolved(request, id):
    Ticket.objects.filter(id=id).update(completed_status=False)
    return HttpResponseRedirect(reverse("ticketapp:ticket-detail", kwargs={"pk": id}))


@login_required
def add_comment(request, ticket_id):
    if request.method == "POST":
        comment = request.POST["comment"]
        ticket = Ticket.objects.get(id=ticket_id)
        user = request.user
        date_time = datetime.datetime.now()
        ticket.resolved_by = user
        ticket.resolved_date = date_time
        ticket.completed_status

        Comment.objects.create(ticket=ticket, user=user, text=comment)
        return HttpResponseRedirect(
            reverse("ticketapp:ticket-detail", kwargs={"pk": ticket_id})
        )


class SearchResultView(LoginRequiredMixin, generic.ListView):
    model = Ticket
    template_name = "ticketapp/search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Ticket.objects.filter(
            Q(title__icontains=query)
            | Q(customer_full_name__icontains=query)
            | Q(issue_description__icontains=query)
        ).filter(user=self.request.user)

        return object_list


class StaffSearchResultView(LoginRequiredMixin, generic.ListView):
    model = Ticket
    template_name = "ticketapp/staff_search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Ticket.objects.filter(
            Q(title__icontains=query)
            | Q(customer_full_name__icontains=query)
            | Q(issue_description__icontains=query)
        ).filter(assigned_to=self.request.user)

        return object_list


class AllSearchResultView(LoginRequiredMixin, generic.ListView):
    model = Ticket
    template_name = "ticketapp/staff_search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Ticket.objects.filter(
            Q(title__icontains=query)
            | Q(customer_full_name__icontains=query)
            | Q(issue_description__icontains=query)
        )

        return object_list


class UserPerformanceListView(LoginRequiredMixin, generic.ListView):
    model = Ticket
    template_name = "ticketapp/charts.html"

    def get_queryset(self):
        queryset = Ticket.objects.values("resolved_by__username").annotate(
            resolved_count=Count("resolved_by")
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        vals = Ticket.objects.values("resolved_by__username").annotate(
            resolved_count=Count("resolved_by")
        )

        my_users = [str(x["resolved_by__username"]) for x in vals]

        if my_users:
            my_users.pop(0)
        context["my_users"] = my_users

        user_num_tickets = [i["resolved_count"] for i in vals]

        if user_num_tickets:
            user_num_tickets.pop(0)

ticketapp/templates/ticketapp/ticket_confirm_delete.html
{% extends 'ticketapp/base.html' %}



{% block content %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        <h1>Are you sure you want to delete: {{object}}?</h1>
        <input type="submit" class="btn btn-danger" value="Delete">
    </form>
</div>


{% endblock content %}

ticketapp/templates/ticketapp/ticket_detail.html
{% extends 'ticketapp/base.html' %}


{% block content %}

<div class="container">
    <h1>{{object.title}}</h1>
    <p>Customer name: {{object.customer_full_name}}</p>
    <p>Phone number: {{object.customer_phone_number}}</p>
    <p>Email: <a href="mailto:{{object.customer_email}}">{{object.customer_email}}</a></p>
    <p>Urgent: {{object.urgent_status}}</p>
    <p>Resolved: {{object.completed_status}}</p>
    <p>Assigned To: {{object.assigned_to.first_name}} {{object.assigned_to.last_name}}</p>
    <p>Created: {{object.created_date}}</p>

    <br>

    <p>{{object.issue_description}}</p>
</div>

<div class="container d-flex mt-2 ">

    {% if user.is_staff %}
        {% if object.completed_status != True %}
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#markResolvedModal">Mark Resolved</button>
        {% endif %}
    {% endif %}
    
    <a href="{% url 'ticketapp:update-ticket' pk=object.pk %}" class="btn btn-primary mx-2">Edit</a>
    <a href="{% url 'ticketapp:delete-ticket' pk=object.pk %}" class="btn btn-danger mx-2">Delete</a>
</div>

{% if comments %}
    <div class="container mt-4">

        <h2>Note</h2>

        {% for comment in comments %}
        <div class="bg-light mt-2 mb-2">
            <p class="text-secondary">@{{comment.user.username}} {{comment.created_date}}</p>
            <p>{{comment.text}}</p>
        </div>

        {% endfor %}
    </div>

{% endif %}

<!-- Modal -->
<div class="modal fade" id="markResolvedModal" tabindex="-1" aria-labelledby="markResolvedModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="markResolvedModalLabel">Add Note</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form action="{% url 'ticketapp:mark-resolved' id=object.pk %}" method="post">
                {% csrf_token %}
                <div class="form-group mt-2 mb-2">
        
                    <textarea name="comment" cols="15" rows="10" class="form-control" placeholder="Add note on how issue was solved..."></textarea>
        
                    <input type="submit" class="btn btn-secondary mt-2">
        
                </div>
        
            </form>
          </div>
        </div>
    </div>
</div>






{% endblock content %}

ticketapp/templates/ticketapp/ticket_form.html
{% extends 'ticketapp/base.html' %}

{% block content %}

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Add Ticket</h1>

<form class="" method="POST">
        {% if form.errors %}
            <ul class="messages">

                {% for error in form.errors %}
                    <li class="danger">{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}


    {% csrf_token %}
    <div class="form-group">
        <label for="id_title">Title</label>
        {{form.title}}
    </div>

    <div class="form-group">
        <label for="id_customer_full_name">Customer full name</label>
        {{form.customer_full_name}}
    </div>

    <div class="form-group">
        <label for="id_customer_phone_number">Phone number</label>
        {{form.customer_phone_number}}
    </div>

    <div class="form-group">
        <label for="id_customer_email">Email</label>
        {{form.customer_email}}
    </div>
    <div class="form-group">
        <label for="id_issue_description">Description</label>
        {{form.issue_description}}
    </div>

    <div class="form-group">
        <label for="id_ticket_section">Select Section</label>
        {{form.ticket_section}}
    </div>

    <div>
        <label for="id_urgent_status">Urgent</label>
        {{form.urgent_status}}
    </div>

    <div class="form-group pt-2 pb-2">
        <label for="id_assigned_to">Assign Technician</label>
        {{form.assigned_to}}
    </div>


    <br>

    <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">Create</button>
    <a href="{% url 'ticketapp:ticket-list' %}" class="w-100 mb-2 btn btn-lg rounded-3 btn-danger" >Cancel</a>

    <hr class="my-4">

</form>


{% endblock content %}

ticketapp/templates/ticketapp/ticket_update.html
{% extends 'ticketapp/base.html' %}

{% block content %}

<div class="container bg-light mt-2 pt-2 pb-4">
    <h1 class="text-center">Update ticket</h1>
    <form action="" method="post">
        {% if form.errors %}
            <ul class="messages">

                {% for error in form.errors %}
                    <li class="text-danger">{{ error }}</li>
                {% endfor %}
            </ul>
        
        {% endif %}


        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Title</label>
            {{form.title}}
        </div>

        <div class="form-group">
            <label for="id_customer_full_name">Customer full name</label>
            {{form.customer_full_name}}
        </div>

        <div class="form-group">
            <label for="id_customer_phone_number">Phone number</label>
            {{form.customer_phone_number}}
        </div>

        <div class="form-group">
            <label for="id_customer_email">Email</label>
            {{form.customer_email}}
        </div>
        <div class="form-group">
            <label for="id_issue_description">Description</label>
            {{form.issue_description}}
        </div>

        <div class="form-group">
            <label for="id_ticket_section">Possible Ticket Category</label>
            {{form.ticket_section}}
        </div>

        <div>
            <label for="id_urgent_status">Urgent</label>
            {{form.urgent_status}}
        </div>

        <div>
            <label for="id_completed_status">Completed</label>
            {{form.completed_status}}
        </div>


        <div class="form-group pt-2 pb-2">
            <label for="id_assigned_to">Assign to</label>
            {{form.assigned_to}}
        </div>

        <input type="submit" class="btn btn-primary">
    </form>
</div>


{% endblock content %}